### ISSUE TITLE
Installer package

### ISSUE THREAD

**Issue by icedterminal** [Lund259/WoW-Addon-Manager#10]
The convenience of having a registered installation would be nice. Like most open source projects I see on the net, they offer portable and install. You could also tie in updates from github. Would you be interested in having an install package?

I've been looking for an alternative to the current addon manager for WoW. And your project looks really good.

**Comment by Lund259** [comment]
That is a very good idea. If you create a pull request i will happily take a look!

**Comment by icedterminal** [comment]
Completed.

**Comment by Lund259** [comment]
@icedterminal I am currently reviewing your pull request. How was the exe installer created?

**Comment by icedterminal** [comment]
Advanced installer Enterprise. Very popular packager.
